### PR TITLE
Migrate Dockerfile to use Ruby 2.7 on Alpine

### PR DESCRIPTION
**Pull request by brainless**
This PR is to migrate the Dockerfile from Ubuntu based to Alpine based. The size difference is:

- 322MB for existing Ubuntu based image
- 171MB for the new Alpine based image in PR

The new Dockerfile is based off of [this official Ruby 2.7 image](https://github.com/docker-library/ruby/blob/8e49e25b591d4cfa6324b6dada4f16629a1e51ce/2.7/alpine3.12/Dockerfile) as [listed here](https://hub.docker.com/_/ruby).

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey @brainless, is this ready for merging? Did you manage to solve previous issue?

**Comment by brainless** [comment]
Yes @eldadfux, when the appwrite containers are running then this container runs fine. I guess the issue was what you mentioned - it needed Redis to be running.

**Comment by brainless** [comment]
@eldadfux is there a way we can run some end - end tests with this new container? Then we should do that to be sure.

**Comment by eldadfux** [comment]
I can try and create a demo docker-compose file and create a simple test for our CI

**Comment by eldadfux** [comment]
I have added a local docker-compose.yml file and a simple HTTP test inside our travis-ci settings, hope it will work, lets wait a few minutes

**Comment by eldadfux** [comment]
The build worked 🥳 and was much faster 👏🏻👏🏻👏🏻

**Pull request merged**
